name: 'Build sphinx docs'

# controls when the workflow will run
on: 
  # triggers on git push
  push:
    branches: [actions]
  
  # allows running this manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    #runs-on: sphinxdoc/sphinx
    runs-on: ubuntu-latest

    steps:
      - name: Testing
        runs:
          using: 'docker'
          image: 'Dockerfile'
